pipeline {
    agent any

    parameters {
        string(name: "NOTIFICATION", defaultValue:"#jenkins-slack-notification", description: "slack notification")
    }

    stages {
        stage("what is git branch") {
            steps {
                slackSend (
                    channel: params.NOTIFICATION,
                    color : "good",
                    message: "----------------- ${env.GIT_BRANCH}-----------------"
                )
            }
        }

        stage("test") {
            when {
                expression {
                    return env.BRANCH_NAME =~ /^deploy\//
                }
            }

            steps {
                slackSend (
                    channel: params.NOTIFICATION,
                    color : "good",
                    message: "----------------- SUCCESS : ${env.BUILD_ID} ${env.GIT_BRANCH}-----------------"
                )
            }
        }

        stage("echo") {

            steps {
                echo "hello world "
            }
        }
    }
}