pipeline {
    agent any

    stages {
        stage("what is git branch") {
            steps {
                env.BRANCH = env.GIT_BRANCH.tokenize('/')[-1]
                echo env.BRANCH
            }
        }

        stage("build image"){
            steps {
                script {
                    if (env.BRANCH == "frontend") {
                        echo "===== frontend ==== "
                    }else if(env.BRANCH == "backend"){
                        echo "===== backend ==== "
                    }else{
                        sh exit 0
                    }
                }
            }
        }
    }
}